import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft, ShieldCheck, Scale, AlertTriangle } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Service | TermsScanner',
  description: 'Terms of Service and legal disclaimer for using TermsScanner AI auditor tool.',
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 font-sans">
      
      {/* Header */}
      <header className="border-b border-slate-800 bg-slate-950/80 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-5xl mx-auto px-4 h-16 flex items-center justify-between">
          <Link
            href="/"
            className="inline-flex items-center space-x-2 text-sm font-semibold text-slate-300 hover:text-white transition-colors"
          >
            <ArrowLeft className="w-4 h-4 text-blue-400" />
            <span>Back to TermsScanner</span>
          </Link>
          <div className="flex items-center space-x-2">
            <ShieldCheck className="w-5 h-5 text-blue-400" />
            <span className="font-bold text-white tracking-tight">TermsScanner</span>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-4 py-12">
        <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-8 sm:p-12 shadow-2xl space-y-8">
          
          <div>
            <span className="inline-flex items-center space-x-1.5 px-3 py-1 bg-blue-950/80 border border-blue-800/60 rounded-full text-xs font-semibold text-blue-300 mb-4">
              <Scale className="w-3.5 h-3.5" />
              <span>User Agreement & Terms</span>
            </span>
            <h1 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
              Terms of Service
            </h1>
            <p className="text-xs text-slate-400 mt-2 font-mono">
              Last Updated: August 12, 2026
            </p>
          </div>

          <hr className="border-slate-800" />

          {/* Legal Disclaimer Box */}
          <div className="p-4 bg-amber-950/40 border border-amber-800/80 rounded-2xl flex items-start space-x-3 text-xs text-amber-200">
            <AlertTriangle className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
            <div>
              <strong className="block text-amber-300 font-bold uppercase tracking-wider mb-1">
                Legal Disclaimer & Not Legal Advice Notice
              </strong>
              <span>
                TermsScanner is an automated AI-assisted analytical software tool. Content generated by TermsScanner does NOT constitute formal legal advice, representation, or a substitute for a qualified licensed attorney. Always consult a legal professional before signing or executing binding legal agreements.
              </span>
            </div>
          </div>

          {/* Terms Content */}
          <div className="space-y-6 text-sm text-slate-300 leading-relaxed">
            
            <section className="space-y-2">
              <h2 className="text-lg font-bold text-white">1. Acceptance of Terms</h2>
              <p>
                By accessing or using TermsScanner (accessible via{' '}
                <a href="https://termsscanner.in" className="text-blue-400 hover:underline">
                  https://termsscanner.in
                </a>
                ), you agree to be bound by these Terms of Service. If you do not agree to all terms, you must immediately discontinue use of the platform.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-lg font-bold text-white">2. Scope of Service</h2>
              <p>
                TermsScanner provides automated document parsing, web scraping, and semantic risk analysis of contracts, NDAs, and privacy policies using artificial intelligence models. The user retains full responsibility for reviewing and verifying any analysis generated by the platform.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-lg font-bold text-white">3. Acceptable Use Policy</h2>
              <p>You agree not to:</p>
              <ul className="list-disc list-inside space-y-1 text-slate-300 pl-2">
                <li>Submit unlawful, malicious, or abusive content to the auditing engine.</li>
                <li>Attempt to bypass rate limits, perform denial-of-service attacks, or reverse-engineer API endpoints.</li>
                <li>Misrepresent AI-generated recommendations as certified legal counsel to third parties.</li>
              </ul>
            </section>

            <section className="space-y-2">
              <h2 className="text-lg font-bold text-white">4. Intellectual Property Rights</h2>
              <p>
                The TermsScanner platform, UI designs, codebases, branding, and algorithms are protected by copyright and intellectual property laws. You retain full ownership of any document text you upload or submit for analysis.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-lg font-bold text-white">5. Limitation of Liability</h2>
              <p>
                To the fullest extent permitted by law, TermsScanner and its creators shall not be liable for any direct, indirect, incidental, or consequential damages resulting from your reliance on automated risk reports, contract audits, or counter-proposal suggestions.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-lg font-bold text-white">6. Modifications to Service & Terms</h2>
              <p>
                We reserve the right to update or modify these Terms of Service at any time. Continued use of TermsScanner following posted updates constitutes acceptance of the modified terms.
              </p>
            </section>

          </div>

          <div className="pt-6 border-t border-slate-800 flex justify-between items-center text-xs text-slate-500">
            <p>© {new Date().getFullYear()} TermsScanner. All rights reserved.</p>
            <div className="flex space-x-4">
              <Link href="/privacy" className="hover:text-slate-300">
                Privacy Policy
              </Link>
              <Link href="/contact" className="hover:text-slate-300">
                Contact Us
              </Link>
            </div>
          </div>

        </div>
      </main>

    </div>
  );
}
