import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft, ShieldCheck, FileText, AlertTriangle } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Service & Limitation of Liability | TermsScanner',
  description: 'Terms of Service detailing user agreement, "As-Is" warranty disclaimer, limitation of liability, and legal non-advice disclosures.',
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 font-sans">
      
      {/* Header */}
      <header className="border-b border-slate-200 bg-white/90 backdrop-blur-md sticky top-0 z-50 shadow-sm">
        <div className="max-w-5xl mx-auto px-4 h-16 flex items-center justify-between">
          <Link
            href="/"
            className="inline-flex items-center space-x-2 text-xs font-bold text-slate-600 hover:text-blue-600 transition-colors"
          >
            <ArrowLeft className="w-4 h-4 text-blue-600" />
            <span>Back to TermsScanner</span>
          </Link>
          <div className="flex items-center space-x-2">
            <ShieldCheck className="w-5 h-5 text-blue-600" />
            <span className="font-extrabold text-slate-900 tracking-tight">TermsScanner</span>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-4 py-12">
        <div className="bg-white border border-slate-200 rounded-3xl p-8 sm:p-12 shadow-xl space-y-8">
          
          <div>
            <span className="inline-flex items-center space-x-1.5 px-3 py-1 bg-amber-50 border border-amber-200 rounded-full text-xs font-bold text-amber-800 mb-4 shadow-sm">
              <AlertTriangle className="w-3.5 h-3.5 text-amber-600" />
              <span>Legal Disclaimers & User Agreement</span>
            </span>
            <h1 className="text-3xl sm:text-4xl font-black text-slate-900 tracking-tight">
              Terms of Service
            </h1>
            <p className="text-xs text-slate-500 mt-2 font-mono">
              Last Updated: August 15, 2026
            </p>
          </div>

          <hr className="border-slate-200" />

          {/* Legal Non-Advice Banner */}
          <div className="p-5 bg-amber-50 border border-amber-200 rounded-2xl flex items-start space-x-3 text-xs text-amber-900">
            <FileText className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
            <div>
              <strong className="block text-amber-950 font-black uppercase tracking-wider mb-1">
                Notice: Informational Automated Heuristic Screening Only
              </strong>
              <span>
                TermsScanner outputs automated heuristic recommendations for general informational purposes only. <strong>Our analysis does not constitute legal advice, formal auditing certification, or an attorney-client relationship.</strong> Always consult a licensed attorney for official legal counsel.
              </span>
            </div>
          </div>

          <div className="space-y-6 text-sm text-slate-700 leading-relaxed">
            
            <section className="space-y-2">
              <h2 className="text-lg font-extrabold text-slate-900">1. Acceptance of Terms</h2>
              <p>
                By accessing or using <strong>TermsScanner</strong> (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, you must cease using the Service immediately.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-lg font-extrabold text-slate-900">2. No Legal Advice Disclaimer</h2>
              <p>
                The outputs, scores, and counter-proposals generated by TermsScanner are created by automated algorithms and artificial intelligence. They do not constitute formal legal opinions or attorney advice. You assume full responsibility for any actions taken based on these outputs.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-lg font-extrabold text-slate-900">3. &quot;As-Is&quot; & &quot;As-Available&quot; Warranty Disclaimer</h2>
              <p>
                THE SERVICE IS PROVIDED STRICTLY &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-lg font-extrabold text-slate-900">4. Limitation of Liability</h2>
              <p>
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL TERMSSCANNER, ITS OPERATORS, AFFILIATES, OR SUPPLIERS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUE ARISING OUT OF YOUR USE OF THE SERVICE.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-lg font-extrabold text-slate-900">5. Contact Information</h2>
              <p>
                Questions regarding these Terms of Service may be addressed to{' '}
                <a href="mailto:support@termsscanner.in" className="text-blue-600 hover:underline font-mono font-bold">
                  support@termsscanner.in
                </a>.
              </p>
            </section>

          </div>

          <div className="pt-6 border-t border-slate-200 flex flex-col sm:flex-row justify-between items-center text-xs text-slate-500 gap-3">
            <p>© {new Date().getFullYear()} TermsScanner. All rights reserved.</p>
            <div className="flex space-x-4 font-bold">
              <Link href="/privacy-policy" className="hover:text-blue-600">
                Privacy Policy
              </Link>
              <Link href="/about" className="hover:text-blue-600">
                About Us
              </Link>
              <Link href="/contact" className="hover:text-blue-600">
                Contact Us
              </Link>
            </div>
          </div>

        </div>
      </main>

    </div>
  );
}
